name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

   
    - name: Convert CSV to JSON
      run: python csvtojson.py

    - name: Run tests
      run: |
        pytest
        # Extra test: Kontrollera att data.json har 900+ rader
        python -c "import json; data = json.load(open('data.json')); assert len(data) >= 900, 'JSON-filen har för få rader!'"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  
        force_orphan: true